spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.46.141:3306/SProjectDatabase?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 114514
  application:
    name: SProjrctBackend
  mail:
    host: smtp.qq.com
    username: hohender@qq.com
    password: filpsiohsmeuchbe
    port: 465
    properties:
      from: hohender@qq.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 0
      host: 117.72.46.141
      port: 6379
      password: 114514
